version: "1.3"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kcs-api
        ports:
            - "4500:4500"
        env_file:
            - .env
        restart: always
