name: Deploy KCS Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Deps
        run: bun install

      - name: Run Tests
        run: bun test || echo "Tests failed"

      - name: Build
        run: bun run build

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kcs-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/kcs-backend:latest

      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/kcs-backend:latest
            docker stop kcs-backend || true && docker rm kcs-backend || true
            docker run -d --name kcs-backend \
              -p 3000:3000 \
              --env-file /home/ubuntu/apps/kcs-backend/.env \
              -v /home/ubuntu/apps/kcs-backend/logs:/app/logs \
              ${{ secrets.DOCKER_USERNAME }}/kcs-backend:latest
